[package]
name = "conduit-wasm"
version = "0.1.0"
authors = ["Jing Li <lijing@dkhs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.9.2"
yew-router = "0.6.1"