[package]
name = "conduit-wasm"
version = "0.1.0"
authors = ["Jet Li <jing.i.qin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# yew = "0.9.2"
yew = {git = "https://github.com/yewstack/yew", branch = "master"}
# yew-router = "0.6.1"
yew-router = {git = "https://github.com/yewstack/yew_router", branch = "master"}