name: Continuous Deployment

on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install cargo-web
      run: cargo install cargo-web
    - name: Build
      run: cargo web deploy --verbose -p conduit-wasm --release
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/deploy
    - name: Package
      shell: bash
      run: |
        cd target
        tar czvf conduit-wasm.tar.gz deploy
        zip -r conduit-wasm.zip deploy
        shasum -a 256 conduit-wasm.tar.gz > conduit-wasm.tar.gz.sha256
        shasum -a 256 conduit-wasm.zip > conduit-wasm.zip.sha256
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/conduit-wasm.tar.gz
          target/conduit-wasm.tar.gz.sha256
          target/conduit-wasm.zip
          target/conduit-wasm.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
