name: deploy

on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Install cargo-web
      run: cargo install cargo-web
    - name: Build
      run: |
        cargo version
        cargo web deploy --verbose -p conduit-wasm --release
        cargo web deploy --verbose -p conduit-wasm --release --output crates/conduit-webview/static
        cargo build --verbose -p conduit-webview --release

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/deploy
    - name: Package
      shell: bash
      run: |
        cd target
        tar czvf conduit-wasm.tar.gz deploy
        zip -r conduit-wasm.zip deploy
        shasum -a 256 conduit-wasm.tar.gz > conduit-wasm.tar.gz.sha256
        shasum -a 256 conduit-wasm.zip > conduit-wasm.zip.sha256
        cd release
        tar czvf conduit-webview-linux.tar.gz conduit-webview
        zip -r conduit-webview-linux.zip conduit-webview
        shasum -a 256 conduit-webview-linux.tar.gz > conduit-webview-linux.tar.gz.sha256
        shasum -a 256 conduit-webview-linux.zip > conduit-webview-linux.zip.sha256
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/conduit-wasm.tar.gz
          target/conduit-wasm.tar.gz.sha256
          target/conduit-wasm.zip
          target/conduit-wasm.zip.sha256
          target/release/conduit-webview-linux.tar.gz
          target/release/conduit-webview-linux.tar.gz.sha256
          target/release/conduit-webview-linux.zip
          target/release/conduit-webview-linux.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
