name: Continuous Integration

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo add-apt-repository ppa:webkit-team/ppa
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Install cargo-web
      run: cargo install cargo-web
    - name: Build
      run: cargo web build --verbose -p conduit-wasm
    - name: Run tests
      run: cargo web test --verbose --nodejs -p conduit-wasm
    - name: cargo fmt & clippy
      run: |
        cargo fmt --all -- --check
        cargo clippy -- --deny=warnings
