name: build

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing needed Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm run install
        npm run build
    - name: Run tests
      run: npm run test
    - name: cargo fmt & clippy
      run: |
        cargo fmt --all -- --check
        cargo clippy -- --deny=warnings
